// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Q-0A3kp2jNR4ipoo7tkXoq9bhCOhG2M',
    appId: '1:679967444799:web:c3fd39dcbc33f3e55c4d8a',
    messagingSenderId: '679967444799',
    projectId: 'ziggly-60826',
    authDomain: 'ziggly-60826.firebaseapp.com',
    storageBucket: 'ziggly-60826.appspot.com',
    measurementId: 'G-KXHQF98JRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8v-g4Iv8YEVOKaDe9adpxLRkptC-77SY',
    appId: '1:679967444799:android:10380e985604a4c35c4d8a',
    messagingSenderId: '679967444799',
    projectId: 'ziggly-60826',
    storageBucket: 'ziggly-60826.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbZPtpWo1PT4_MNY6SesNMUrbO8tCKj8Q',
    appId: '1:679967444799:ios:8a3da18e961b85e55c4d8a',
    messagingSenderId: '679967444799',
    projectId: 'ziggly-60826',
    storageBucket: 'ziggly-60826.appspot.com',
    androidClientId: '679967444799-6a7tl4l6f7tdc5q6s4760d7mjo08v93e.apps.googleusercontent.com',
    iosClientId: '679967444799-um6os6lgbkv6hj84fgafvdn53hdpv3qn.apps.googleusercontent.com',
    iosBundleId: 'com.signimus.ziggly.mysalon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbZPtpWo1PT4_MNY6SesNMUrbO8tCKj8Q',
    appId: '1:679967444799:ios:8a3da18e961b85e55c4d8a',
    messagingSenderId: '679967444799',
    projectId: 'ziggly-60826',
    storageBucket: 'ziggly-60826.appspot.com',
    androidClientId: '679967444799-6a7tl4l6f7tdc5q6s4760d7mjo08v93e.apps.googleusercontent.com',
    iosClientId: '679967444799-um6os6lgbkv6hj84fgafvdn53hdpv3qn.apps.googleusercontent.com',
    iosBundleId: 'com.signimus.ziggly.mysalon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_Q-0A3kp2jNR4ipoo7tkXoq9bhCOhG2M',
    appId: '1:679967444799:web:985938742d3b4a375c4d8a',
    messagingSenderId: '679967444799',
    projectId: 'ziggly-60826',
    authDomain: 'ziggly-60826.firebaseapp.com',
    storageBucket: 'ziggly-60826.appspot.com',
    measurementId: 'G-BLWTKW1Z5V',
  );
}
